SELECT
    CAST([YEARTXT] AS INT) AS [ModelYear],
    COUNT(*) AS [CrashCount]
FROM [dbo].[FordExternalTable]
WHERE UPPER(LTRIM(RTRIM([MODELTXT]))) = 'F-150'
  AND CAST([YEARTXT] AS INT) BETWEEN 1990 AND 2010
  AND UPPER(LTRIM(RTRIM([CRASH]))) IN ('Y', 'TRUE')
GROUP BY CAST([YEARTXT] AS INT)
ORDER BY [ModelYear] ASC;